default["freeipa"]["ipa_admin_password"] = "ipa_admin_password"
default["freeipa"]["hostname"] = "host.example.com"
default["freeipa"]["domain"] = "example.com"
default["freeipa"]["dir_manager_password"] = "dir_manager_password"
default["freeipa"]["realm_name"] = "example.com"
